package com.example.myapplication.dataprocess


import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
class DataInitHelper {
    companion object {
        suspend fun initTestData() {
            withContext(Dispatchers.IO) {
                val dao = AppDatabase.instance.adItemDao()
                // 检查数据库是否已有数据
                val existingCount = dao.getItemsSync(0, 0, 1).size
                
                if (existingCount == 0) {
                    // 数据库为空，初始化测试数据
                    val list = mutableListOf<AdItem>()
                    
                    list.addAll(
                    listOf(
                        AdItem(
                            id = "1",
                            title = "AI智能推荐广告",
                            desc = "基于大数据AI生成的个性化推荐内容，精准触达用户",
                            detailContent = "基于大数据AI生成的个性化推荐内容，精准触达用户，为你带来更高效的体验",
                            label = listOf("推荐", "高效", "精准"),
                            imgUrl = "https://picsum.photos/600/300?random=1",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 1256,
                            starCount = 89
                        ),
                        AdItem(
                            id = "2",
                            title = "本地生活特惠",
                            desc = "周边美食、娱乐、出行一站式优惠，每日更新",
                            detailContent = "周边美食、娱乐、出行一站式优惠，每日更新，省钱更省心",
                            label = listOf("本地", "特惠", "生活"),
                            imgUrl = "https://picsum.photos/600/300?random=2",
                            videoUrl = null,
                            type = 1,
                            channelType = 0,
                            likeCount = 3421,
                            starCount = 256
                        ),
                        AdItem(
                            id = "3",
                            title = "短视频创意广告",
                            desc = "高清创意短视频，视觉冲击力强，转化效果极佳",
                            detailContent = "高清创意短视频，视觉冲击力强，转化效果极佳，适合品牌宣传",
                            label = listOf("短视频", "创意", "热门"),
                            imgUrl = "https://picsum.photos/600/300?random=3",
                            videoUrl = "https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "4",
                            title = "电商好物推荐",
                            desc = "全网热销商品实时推荐，性价比超高",
                            detailContent = "全网热销商品实时推荐，性价比超高，品质保障放心购",
                            label = listOf("电商", "好物", "特价"),
                            imgUrl = "https://picsum.photos/600/300?random=4",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "5",
                            title = "学习提升课程",
                            desc = "职场技能、语言学习、兴趣爱好全面提升",
                            detailContent = "职场技能、语言学习、兴趣爱好全面提升，成就更好的自己",
                            label = listOf("学习", "提升", "成长"),
                            imgUrl = "https://picsum.photos/600/300?random=5",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "6",
                            title = "旅行攻略推荐",
                            desc = "全球热门景点攻略，省钱又省心",
                            detailContent = "全球热门景点攻略，省钱又省心，自由行必备攻略",
                            label = listOf("旅行", "攻略", "自由行"),
                            imgUrl = "https://picsum.photos/600/300?random=6",
                            videoUrl = "https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "7",
                            title = "健康生活指南",
                            desc = "科学饮食、运动健身、健康生活小知识",
                            detailContent = "科学饮食、运动健身、健康生活小知识，守护家人健康",
                            label = listOf("健康", "养生", "运动"),
                            imgUrl = "https://picsum.photos/600/300?random=7",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "8",
                            title = "美妆护肤精选",
                            desc = "正品美妆、护肤好物，女生必备",
                            detailContent = "正品美妆、护肤好物，女生必备，焕活肌肤美丽",
                            label = listOf("美妆", "护肤", "正品"),
                            imgUrl = "https://picsum.photos/600/300?random=8",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "9",
                            title = "汽车资讯推荐",
                            desc = "新车报价、评测、用车技巧全知道",
                            detailContent = "新车报价、评测、用车技巧全知道，爱车人士必备",
                            label = listOf("汽车", "资讯", "用车"),
                            imgUrl = "https://picsum.photos/600/300?random=9",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "10",
                            title = "数码科技新品",
                            desc = "手机、电脑、数码产品最新发布",
                            detailContent = "手机、电脑、数码产品最新发布，科技前沿抢先看",
                            label = listOf("数码", "科技", "新品"),
                            imgUrl = "https://picsum.photos/600/300?random=10",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "11",
                            title = "美食菜谱分享",
                            desc = "家常菜、烘焙、小吃简单易学",
                            detailContent = "家常菜、烘焙、小吃简单易学，在家轻松做大厨",
                            label = listOf("美食", "菜谱", "家常菜"),
                            imgUrl = "https://picsum.photos/600/300?random=11",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "12",
                            title = "家居好物推荐",
                            desc = "实用家居、收纳神器、品质生活",
                            detailContent = "实用家居、收纳神器、品质生活，提升居家幸福感",
                            label = listOf("家居", "收纳", "品质"),
                            imgUrl = "https://picsum.photos/600/300?random=12",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "13",
                            title = "职场效率工具",
                            desc = "提高工作效率，时间管理必备",
                            detailContent = "提高工作效率，时间管理必备，职场人进阶神器",
                            label = listOf("职场", "效率", "工具"),
                            imgUrl = "https://picsum.photos/600/300?random=13",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "14",
                            title = "宠物喂养指南",
                            desc = "科学养宠、健康喂养、日常护理",
                            detailContent = "科学养宠、健康喂养、日常护理，萌宠健康成长",
                            label = listOf("宠物", "喂养", "可爱"),
                            imgUrl = "https://picsum.photos/600/300?random=14",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "15",
                            title = "时尚穿搭推荐",
                            desc = "四季穿搭、潮流搭配、气质提升",
                            detailContent = "四季穿搭、潮流搭配、气质提升，轻松变美变帅",
                            label = listOf("时尚", "穿搭", "潮流"),
                            imgUrl = "https://picsum.photos/600/300?random=15",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "16",
                            title = "母婴用品精选",
                            desc = "宝妈必备，安全放心母婴好物",
                            detailContent = "宝妈必备，安全放心母婴好物，呵护宝宝成长",
                            label = listOf("母婴", "宝宝", "安全"),
                            imgUrl = "https://picsum.photos/600/300?random=16",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "17",
                            title = "运动健身课程",
                            desc = "居家健身、燃脂塑形、专业指导",
                            detailContent = "居家健身、燃脂塑形、专业指导，足不出户练出好身材",
                            label = listOf("运动", "健身", "居家"),
                            imgUrl = "https://picsum.photos/600/300?random=17",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "18",
                            title = "电影综艺推荐",
                            desc = "热门影视、高分综艺实时更新",
                            detailContent = "热门影视、高分综艺实时更新，休闲娱乐好选择",
                            label = listOf("影视", "综艺", "娱乐"),
                            imgUrl = "https://picsum.photos/600/300?random=18",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "19",
                            title = "投资理财指南",
                            desc = "稳健理财、资产配置、风险控制",
                            detailContent = "稳健理财、资产配置、风险控制，财富增值更安心",
                            label = listOf("理财", "投资", "稳健"),
                            imgUrl = "https://picsum.photos/600/300?random=19",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "20",
                            title = "阅读好书推荐",
                            desc = "提升自我，丰富内心，每日阅读",
                            detailContent = "提升自我，丰富内心，每日阅读，遇见更好的自己",
                            label = listOf("阅读", "书籍", "成长"),
                            imgUrl = "https://picsum.photos/600/300?random=20",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "21",
                            title = "音乐歌单推荐",
                            desc = "热门歌曲、经典老歌、个性推荐",
                            detailContent = "热门歌曲、经典老歌、个性推荐，随时随地听好歌",
                            label = listOf("音乐", "歌单", "热门"),
                            imgUrl = "https://picsum.photos/600/300?random=21",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "22",
                            title = "摄影技巧分享",
                            desc = "手机摄影、构图技巧、后期处理",
                            detailContent = "手机摄影、构图技巧、后期处理，随手拍出大片感",
                            label = listOf("摄影", "技巧", "手机"),
                            imgUrl = "https://picsum.photos/600/300?random=22",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "23",
                            title = "手工DIY教程",
                            desc = "创意手工、废物利用、亲子互动",
                            detailContent = "创意手工、废物利用、亲子互动，乐趣满满超治愈",
                            label = listOf("手工", "DIY", "创意"),
                            imgUrl = "https://picsum.photos/600/300?random=23",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "24",
                            title = "游戏攻略推荐",
                            desc = "热门手游、端游攻略、通关技巧",
                            detailContent = "热门手游、端游攻略、通关技巧，轻松成为游戏大神",
                            label = listOf("游戏", "攻略", "手游"),
                            imgUrl = "https://picsum.photos/600/300?random=24",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "25",
                            title = "教育培训资讯",
                            desc = "升学、考试、培训全面资讯",
                            detailContent = "升学、考试、培训全面资讯，助力学业进步",
                            label = listOf("教育", "培训", "考试"),
                            imgUrl = "https://picsum.photos/600/300?random=25",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "26",
                            title = "装修设计指南",
                            desc = "简约、轻奢、中式风格装修灵感",
                            detailContent = "简约、轻奢、中式风格装修灵感，打造理想家园",
                            label = listOf("装修", "设计", "家居"),
                            imgUrl = "https://picsum.photos/600/300?random=26",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "27",
                            title = "鲜花礼品推荐",
                            desc = "节日送礼、生日惊喜、浪漫表达",
                            detailContent = "节日送礼、生日惊喜、浪漫表达，传递温暖心意",
                            label = listOf("鲜花", "礼品", "浪漫"),
                            imgUrl = "https://picsum.photos/600/300?random=27",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "28",
                            title = "法律知识科普",
                            desc = "日常法律常识、维权小知识",
                            detailContent = "日常法律常识、维权小知识，学会用法律保护自己",
                            label = listOf("法律", "科普", "维权"),
                            imgUrl = "https://picsum.photos/600/300?random=28",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "29",
                            title = "心理情绪疏导",
                            desc = "缓解压力、调节情绪、心理健康",
                            detailContent = "缓解压力、调节情绪、心理健康，守护心灵健康",
                            label = listOf("心理", "情绪", "健康"),
                            imgUrl = "https://picsum.photos/600/300?random=29",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "30",
                            title = "招聘求职信息",
                            desc = "优质岗位、求职技巧、职场指南",
                            detailContent = "优质岗位、求职技巧、职场指南，找到心仪好工作",
                            label = listOf("招聘", "求职", "职场"),
                            imgUrl = "https://picsum.photos/600/300?random=30",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "31",
                            title = "咖啡饮品指南",
                            desc = "精品咖啡、自制饮品、下午茶",
                            detailContent = "精品咖啡、自制饮品、下午茶，享受惬意时光",
                            label = listOf("咖啡", "饮品", "下午茶"),
                            imgUrl = "https://picsum.photos/600/300?random=31",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "32",
                            title = "绿植养护教程",
                            desc = "室内绿植、盆栽养护、净化空气",
                            detailContent = "室内绿植、盆栽养护、净化空气，装点温馨小家",
                            label = listOf("绿植", "养护", "盆栽"),
                            imgUrl = "https://picsum.photos/600/300?random=32",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "33",
                            title = "潮流玩具推荐",
                            desc = "手办、盲盒、潮玩收藏",
                            detailContent = "手办、盲盒、潮玩收藏，收藏属于你的快乐",
                            label = listOf("潮玩", "手办", "盲盒"),
                            imgUrl = "https://picsum.photos/600/300?random=33",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "34",
                            title = "白酒红酒推荐",
                            desc = "品质酒水、送礼自饮皆宜",
                            detailContent = "品质酒水、送礼自饮皆宜，口感醇厚品质保障",
                            label = listOf("酒水", "白酒", "红酒"),
                            imgUrl = "https://picsum.photos/600/300?random=34",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "35",
                            title = "零食美食推荐",
                            desc = "网红零食、地方特产、美味小吃",
                            detailContent = "网红零食、地方特产、美味小吃，吃货必备福利",
                            label = listOf("零食", "美食", "特产"),
                            imgUrl = "https://picsum.photos/600/300?random=35",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "36",
                            title = "舞蹈教学视频",
                            desc = "流行舞、爵士舞、简单易学",
                            detailContent = "流行舞、爵士舞、简单易学，零基础也能轻松学会",
                            label = listOf("舞蹈", "教学", "流行"),
                            imgUrl = "https://picsum.photos/600/300?random=36",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "37",
                            title = "书法绘画教程",
                            desc = "毛笔字、国画、素描基础教学",
                            detailContent = "毛笔字、国画、素描基础教学，陶冶情操提升气质",
                            label = listOf("书法", "绘画", "艺术"),
                            imgUrl = "https://picsum.photos/600/300?random=37",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "38",
                            title = "渔具户外推荐",
                            desc = "钓鱼装备、户外露营必备",
                            detailContent = "钓鱼装备、户外露营必备，享受大自然乐趣",
                            label = listOf("户外", "渔具", "露营"),
                            imgUrl = "https://picsum.photos/600/300?random=38",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "39",
                            title = "宠物短视频",
                            desc = "萌宠日常、搞笑瞬间、治愈系",
                            detailContent = "萌宠日常、搞笑瞬间、治愈系，看完心情超美好",
                            label = listOf("萌宠", "搞笑", "治愈"),
                            imgUrl = "https://picsum.photos/600/300?random=39",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "40",
                            title = "智能家居推荐",
                            desc = "智能家电、便捷生活、科技感",
                            detailContent = "智能家电、便捷生活、科技感，开启智慧新生活",
                            label = listOf("智能", "家居", "科技"),
                            imgUrl = "https://picsum.photos/600/300?random=40",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "41",
                            title = "美甲美妆教程",
                            desc = "简约美甲、日常妆容、快速上手",
                            detailContent = "简约美甲、日常妆容、快速上手，变美就是这么简单",
                            label = listOf("美甲", "美妆", "教程"),
                            imgUrl = "https://picsum.photos/600/300?random=41",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "42",
                            title = "健身减脂餐指南",
                            desc = "健身餐、减脂餐、高蛋白食谱",
                            detailContent = "健身餐、减脂餐、高蛋白食谱，吃着就能瘦",
                            label = listOf("健身餐", "减脂", "健康"),
                            imgUrl = "https://picsum.photos/600/300?random=42",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "43",
                            title = "考试考证指南",
                            desc = "公考、教资、会计考试攻略",
                            detailContent = "公考、教资、会计考试攻略，备考通关更轻松",
                            label = listOf("考试", "考证", "攻略"),
                            imgUrl = "https://picsum.photos/600/300?random=43",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "44",
                            title = "亲子互动游戏",
                            desc = "亲子陪伴、益智游戏、快乐成长",
                            detailContent = "亲子陪伴、益智游戏、快乐成长，温馨亲子时光",
                            label = listOf("亲子", "游戏", "益智"),
                            imgUrl = "https://picsum.photos/600/300?random=44",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "45",
                            title = "街头美食探店",
                            desc = "各地特色小吃、路边摊美味",
                            detailContent = "各地特色小吃、路边摊美味，探寻人间烟火气",
                            label = listOf("美食", "探店", "街头"),
                            imgUrl = "https://picsum.photos/600/300?random=45",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "46",
                            title = "奢侈品精选推荐",
                            desc = "包包、手表、首饰精选",
                            detailContent = "包包、手表、首饰精选，高端品质彰显格调",
                            label = listOf("奢侈品", "高端", "精选"),
                            imgUrl = "https://picsum.photos/600/300?random=46",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "47",
                            title = "学生文具好物",
                            desc = "学生党、办公党必备文具",
                            detailContent = "学生党、办公党必备文具，学习工作更高效",
                            label = listOf("文具", "办公", "学生"),
                            imgUrl = "https://picsum.photos/600/300?random=47",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "48",
                            title = "瑜伽冥想教学",
                            desc = "舒缓身心、提升气质、静心冥想",
                            detailContent = "舒缓身心、提升气质、静心冥想，放松身心缓解疲惫",
                            label = listOf("瑜伽", "冥想", "舒缓"),
                            imgUrl = "https://picsum.photos/600/300?random=48",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "49",
                            title = "高性价比二手车",
                            desc = "靠谱二手车、性价比高、车况透明",
                            detailContent = "靠谱二手车、性价比高、车况透明，买车更放心",
                            label = listOf("二手车", "汽车", "性价比"),
                            imgUrl = "https://picsum.photos/600/300?random=49",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "50",
                            title = "房产租房指南",
                            desc = "租房避坑、买房攻略、房源推荐",
                            detailContent = "租房避坑、买房攻略、房源推荐，安居更轻松",
                            label = listOf("房产", "租房", "买房"),
                            imgUrl = "https://picsum.photos/600/300?random=50",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "51",
                            title = "趣味魔术教学",
                            desc = "简单魔术、聚会表演、趣味十足",
                            detailContent = "简单魔术、聚会表演、趣味十足，成为全场焦点",
                            label = listOf("魔术", "教学", "表演"),
                            imgUrl = "https://picsum.photos/600/300?random=51",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "52",
                            title = "编程入门教程",
                            desc = "Python、Java、前端入门教程",
                            detailContent = "Python、Java、前端入门教程，零基础轻松学编程",
                            label = listOf("编程", "学习", "IT"),
                            imgUrl = "https://picsum.photos/600/300?random=52",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "53",
                            title = "发型造型设计",
                            desc = "男生发型、女生发型、脸型搭配",
                            detailContent = "男生发型、女生发型、脸型搭配，颜值瞬间提升",
                            label = listOf("发型", "造型", "美发"),
                            imgUrl = "https://picsum.photos/600/300?random=53",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "54",
                            title = "娱乐圈娱乐资讯",
                            desc = "娱乐圈动态、明星八卦、热门话题",
                            detailContent = "娱乐圈动态、明星八卦、热门话题，吃瓜不迷路",
                            label = listOf("娱乐", "明星", "八卦"),
                            imgUrl = "https://picsum.photos/600/300?random=54",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "55",
                            title = "居家风水科普",
                            desc = "家居风水、财位布局、运势提升",
                            detailContent = "家居风水、财位布局、运势提升，旺家旺运",
                            label = listOf("风水", "布局", "运势"),
                            imgUrl = "https://picsum.photos/600/300?random=55",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "56",
                            title = "个性礼品定制",
                            desc = "个性定制、纪念礼品、创意礼物",
                            detailContent = "个性定制、纪念礼品、创意礼物，心意更特别",
                            label = listOf("定制", "礼品", "创意"),
                            imgUrl = "https://picsum.photos/600/300?random=56",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "57",
                            title = "街头滑板教学",
                            desc = "滑板技巧、街头潮流、极限运动",
                            detailContent = "滑板技巧、街头潮流、极限运动，酷盖必备技能",
                            label = listOf("滑板", "运动", "潮流"),
                            imgUrl = "https://picsum.photos/600/300?random=57",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "58",
                            title = "茶叶茶具选购",
                            desc = "绿茶、红茶、普洱茶、品质茶具",
                            detailContent = "绿茶、红茶、普洱茶、品质茶具，品茶品味品人生",
                            label = listOf("茶叶", "茶具", "养生"),
                            imgUrl = "https://picsum.photos/600/300?random=58",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "59",
                            title = "舒适内衣家居服",
                            desc = "舒适内衣、居家睡衣、亲肤透气",
                            detailContent = "舒适内衣、居家睡衣、亲肤透气，居家舒适一整天",
                            label = listOf("内衣", "家居服", "舒适"),
                            imgUrl = "https://picsum.photos/600/300?random=59",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "60",
                            title = "热门演唱会资讯",
                            desc = "热门演出、音乐节、线下活动",
                            detailContent = "热门演出、音乐节、线下活动，现场嗨翻天",
                            label = listOf("演唱会", "演出", "音乐"),
                            imgUrl = "https://picsum.photos/600/300?random=60",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "61",
                            title = "手机配件优选",
                            desc = "手机壳、充电器、耳机精选",
                            detailContent = "手机壳、充电器、耳机精选，实用又好看",
                            label = listOf("手机", "配件", "数码"),
                            imgUrl = "https://picsum.photos/600/300?random=61",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "62",
                            title = "电竞电脑配件",
                            desc = "显卡、内存、机械键盘精选",
                            detailContent = "显卡、内存、机械键盘精选，游戏体验拉满",
                            label = listOf("电脑", "配件", "电竞"),
                            imgUrl = "https://picsum.photos/600/300?random=62",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "63",
                            title = "萌娃日常记录",
                            desc = "可爱宝宝、成长瞬间、治愈系",
                            detailContent = "可爱宝宝、成长瞬间、治愈系，暖心成长时光",
                            label = listOf("萌娃", "成长", "治愈"),
                            imgUrl = "https://picsum.photos/600/300?random=63",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "64",
                            title = "小成本创业项目",
                            desc = "小本创业、副业赚钱、商机分析",
                            detailContent = "小本创业、副业赚钱、商机分析，轻松开启副业",
                            label = listOf("创业", "副业", "商机"),
                            imgUrl = "https://picsum.photos/600/300?random=64",
                            videoUrl = null,
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "65",
                            title = "闲置二手好物",
                            desc = "二手物品、低价捡漏、环保循环",
                            detailContent = "二手物品、低价捡漏、环保循环，省钱又环保",
                            label = listOf("二手", "闲置", "性价比"),
                            imgUrl = "https://picsum.photos/600/300?random=65",
                            videoUrl = null,
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "66",
                            title = "居家生活小妙招",
                            desc = "实用生活技巧、省时省力小妙招",
                            detailContent = "实用生活技巧、省时省力小妙招，生活更轻松",
                            label = listOf("生活", "技巧", "实用"),
                            imgUrl = "https://picsum.photos/600/300?random=66",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        )
                    )
                )
                list.addAll(
                    listOf(
                        AdItem(
                            id = "67",
                            title = "智能家居全屋定制",
                            desc = "一站式智能家装方案，语音控制全屋设备，提升生活品质",
                            detailContent = "详情页完整内容：专业全屋智能定制，包含灯光、窗帘、家电、安防全系统，语音+APP双控制，免费上门设计安装，售后终身维护",
                            label = listOf("智能", "全屋", "定制"),
                            imgUrl = "https://picsum.photos/600/300?random=67",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "68",
                            title = "网红早餐速食推荐",
                            desc = "5分钟搞定营养早餐，懒人必备，好吃不胖超方便",
                            detailContent = "详情页完整内容：精选10款网红速食早餐，免煮免开火，开水冲泡即食，低脂高蛋白，适合学生党上班族，健康又省时",
                            label = listOf("早餐", "速食", "懒人"),
                            imgUrl = "https://picsum.photos/600/300?random=68",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "69",
                            title = "户外露营装备大全",
                            desc = "露营必备装备清单，轻量化出行，野外舒适体验",
                            detailContent = "详情页完整内容：新手露营全套装备推荐，帐篷睡袋防潮垫、炊具灯具桌椅，轻量化设计便携易收纳，野外露营安全感拉满",
                            label = listOf("露营", "户外", "装备"),
                            imgUrl = "https://picsum.photos/600/300?random=69",
                            videoUrl = "https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "70",
                            title = "平价护肤套装测评",
                            desc = "学生党护肤好物，温和不刺激，补水保湿一步到位",
                            detailContent = "详情页完整内容：百元内高性价比护肤套装实测，洁面水乳三件套，温和补水不闷痘，敏感肌可用，平价不输大牌",
                            label = listOf("护肤", "平价", "学生"),
                            imgUrl = "https://picsum.photos/600/300?random=70",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "71",
                            title = "职场沟通技巧课程",
                            desc = "高情商沟通方法，汇报表达更清晰，升职加薪更快",
                            detailContent = "详情页完整内容：职场高情商沟通必修课，汇报技巧、同事相处、向上管理、会议表达，学会轻松搞定职场人际关系",
                            label = listOf("职场", "沟通", "情商"),
                            imgUrl = "https://picsum.photos/600/300?random=71",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "72",
                            title = "城市夜景拍摄教程",
                            desc = "手机拍夜景大片，参数设置技巧，随手出大片",
                            detailContent = "详情页完整内容：手机夜景拍摄万能参数教程，ISO、快门、白平衡调节，构图技巧+后期滤镜，新手也能拍出国风大片",
                            label = listOf("摄影", "夜景", "手机"),
                            imgUrl = "https://picsum.photos/600/300?random=72",
                            videoUrl = "https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/mp4/xgplayer-demo-720p.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "73",
                            title = "养生茶饮配方分享",
                            desc = "四季养生茶搭配，补气养颜去火，适合各类体质",
                            detailContent = "详情页完整内容：20款家常养生茶配方，补气养血、清热去火、祛湿健脾，食材简单易买，在家就能煮，全家都能喝",
                            label = listOf("养生", "茶饮", "健康"),
                            imgUrl = "https://picsum.photos/600/300?random=73",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "74",
                            title = "平价彩妆全套推荐",
                            desc = "新手化妆全套工具，自然妆感，性价比超高",
                            detailContent = "详情页完整内容：新手入门彩妆套装清单，底妆眼妆唇妆全套，平价好用不踩雷，自然伪素颜，学生党闭眼入",
                            label = listOf("彩妆", "新手", "平价"),
                            imgUrl = "https://picsum.photos/600/300?random=74",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "75",
                            title = "电动车选购指南",
                            desc = "新手买电动车必看，续航、安全、性价比全攻略",
                            detailContent = "详情页完整内容：2025电动车选购避坑指南，续航电池、刹车安全、牌照政策、品牌对比，花少钱买好车",
                            label = listOf("电动车", "选购", "攻略"),
                            imgUrl = "https://picsum.photos/600/300?random=75",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "76",
                            title = "桌面收纳改造技巧",
                            desc = "小空间大利用，书桌整洁收纳，办公学习更高效",
                            detailContent = "详情页完整内容：小户型桌面收纳改造方案，收纳盒分层架合理利用空间，整洁美观，办公学习效率翻倍",
                            label = listOf("收纳", "桌面", "改造"),
                            imgUrl = "https://picsum.photos/600/300?random=76",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "77",
                            title = "低卡零食大合集",
                            desc = "解馋不发胖，追剧必备，健康无负担零食",
                            detailContent = "详情页完整内容：30款低卡低脂零食推荐，热量低口感好，追剧解馋无负担，减脂期也能放心吃",
                            label = listOf("零食", "低卡", "解馋"),
                            imgUrl = "https://picsum.photos/600/300?random=77",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "78",
                            title = "家庭绿植布置方案",
                            desc = "室内好养绿植，净化空气，美化家居环境",
                            detailContent = "详情页完整内容：15款室内超好养绿植，耐阴耐旱，净化空气除甲醛，客厅卧室阳台全覆盖，新手也能养爆盆",
                            label = listOf("绿植", "家庭", "好养"),
                            imgUrl = "https://picsum.photos/600/300?random=78",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "79",
                            title = "手机省电优化技巧",
                            desc = "延长续航时间，关闭耗电设置，手机更耐用",
                            detailContent = "详情页完整内容：手机隐藏省电设置教程，关闭后台耗电、调整屏幕亮度、禁用无用通知，续航直接翻倍",
                            label = listOf("手机", "省电", "优化"),
                            imgUrl = "https://picsum.photos/600/300?random=79",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "80",
                            title = "猫咪喂养护理指南",
                            desc = "新手养猫必备，科学喂养，健康陪伴",
                            detailContent = "详情页完整内容：新手养猫全攻略，猫粮选择、疫苗驱虫、日常护理、行为训练，科学养宠少生病",
                            label = listOf("猫咪", "喂养", "护理"),
                            imgUrl = "https://picsum.photos/600/300?random=80",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "81",
                            title = "街头潮流穿搭分享",
                            desc = "日常百搭穿搭，简约时尚，男女都适合",
                            detailContent = "详情页完整内容：春夏街头潮流穿搭合集，简约百搭不挑人，男女同款，平价穿出高级感，日常出门超吸睛",
                            label = listOf("穿搭", "潮流", "街头"),
                            imgUrl = "https://picsum.photos/600/300?random=81",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "82",
                            title = "宝宝辅食制作教程",
                            desc = "营养均衡辅食，简单易做，宝宝超爱吃",
                            detailContent = "详情页完整内容：6-12月龄宝宝辅食食谱，荤素搭配营养均衡，做法简单快手，软烂易消化，宝宝爱吃不挑食",
                            label = listOf("宝宝", "辅食", "营养"),
                            imgUrl = "https://picsum.photos/600/300?random=82",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "83",
                            title = "居家拉伸放松课程",
                            desc = "久坐舒缓拉伸，缓解腰酸背痛，10分钟见效",
                            detailContent = "详情页完整内容：上班族居家拉伸教程，10分钟舒缓肩颈腰背痛，改善久坐僵硬，放松全身超舒服",
                            label = listOf("拉伸", "居家", "放松"),
                            imgUrl = "https://picsum.photos/600/300?random=83",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "84",
                            title = "高分纪录片推荐",
                            desc = "涨知识纪录片，开阔眼界，休闲学习两不误",
                            detailContent = "详情页完整内容：20部必看高分纪录片，自然历史人文科技全覆盖，休闲时光涨知识，大人小孩都适合",
                            label = listOf("纪录片", "高分", "知识"),
                            imgUrl = "https://picsum.photos/600/300?random=84",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "85",
                            title = "零钱理财小技巧",
                            desc = "低风险理财方法，小钱也能赚收益",
                            detailContent = "详情页完整内容：新手零钱理财攻略，低风险稳健收益，门槛低操作简单，零花钱也能钱生钱",
                            label = listOf("理财", "零钱", "低风险"),
                            imgUrl = "https://picsum.photos/600/300?random=85",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "86",
                            title = "治愈系书籍推荐",
                            desc = "温暖治愈书单，缓解焦虑，治愈内心",
                            detailContent = "详情页完整内容：15本治愈系暖心书籍，文字温柔治愈，缓解压力焦虑，适合睡前阅读，治愈所有不开心",
                            label = listOf("书籍", "治愈", "温暖"),
                            imgUrl = "https://picsum.photos/600/300?random=86",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "87",
                            title = "助眠白噪音合集",
                            desc = "改善失眠质量，深度睡眠，放松解压",
                            detailContent = "详情页完整内容：精选助眠白噪音合集，雨声溪流声森林声，放松大脑快速入睡，改善失眠多梦",
                            label = listOf("助眠", "白噪音", "放松"),
                            imgUrl = "https://picsum.photos/600/300?random=87",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "88",
                            title = "vlog拍摄剪辑教程",
                            desc = "新手拍vlog技巧，手机剪辑，轻松出片",
                            detailContent = "详情页完整内容：新手vlog拍摄+剪辑全教程，手机就能操作，运镜转场+剪辑技巧，轻松拍出高质量vlog",
                            label = listOf("vlog", "拍摄", "剪辑"),
                            imgUrl = "https://picsum.photos/600/300?random=88",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "89",
                            title = "旧物改造创意手工",
                            desc = "废品变宝贝，环保实用，亲子手工超有趣",
                            detailContent = "详情页完整内容：废旧物品创意改造教程，纸箱瓶子变废为宝，实用又美观，亲子互动超有趣还环保",
                            label = listOf("手工", "旧物改造", "创意"),
                            imgUrl = "https://picsum.photos/600/300?random=89",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "90",
                            title = "手游画质优化设置",
                            desc = "提升游戏流畅度，高清画质，不卡顿",
                            detailContent = "详情页完整内容：手游画质优化隐藏设置，提升帧率清晰度，降低卡顿发热，低端机也能流畅玩大作",
                            label = listOf("游戏", "优化", "画质"),
                            imgUrl = "https://picsum.photos/600/300?random=90",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "91",
                            title = "考研复习规划攻略",
                            desc = "高效复习计划，时间管理，上岸必备",
                            detailContent = "详情页完整内容：考研全年复习规划，各科学习方法+时间安排，高效备考不迷路，零基础也能稳稳上岸",
                            label = listOf("考研", "复习", "规划"),
                            imgUrl = "https://picsum.photos/600/300?random=91",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "92",
                            title = "小户型装修设计",
                            desc = "空间最大化利用，简约温馨，小窝大变样",
                            detailContent = "详情页完整内容：小户型装修设计攻略，简约风格温馨舒适，空间利用率拉满，小房子也能住出大感觉",
                            label = listOf("装修", "小户型", "设计"),
                            imgUrl = "https://picsum.photos/600/300?random=92",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "93",
                            title = "节日礼物挑选指南",
                            desc = "送礼不踩雷，男女老少都适合的礼物",
                            detailContent = "详情页完整内容：节日送礼万能指南，男女朋友长辈小孩全覆盖，实用有心意，再也不用愁送什么",
                            label = listOf("礼物", "挑选", "节日"),
                            imgUrl = "https://picsum.photos/600/300?random=93",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "94",
                            title = "社保医保使用指南",
                            desc = "社保医保报销技巧，实用干货，少花冤枉钱",
                            detailContent = "详情页完整内容：社保医保使用全攻略，报销流程、异地就医、个人账户使用，看懂少花很多冤枉钱",
                            label = listOf("社保", "医保", "实用"),
                            imgUrl = "https://picsum.photos/600/300?random=94",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "95",
                            title = "压力情绪管理方法",
                            desc = "缓解职场压力，调节情绪，保持好心态",
                            detailContent = "详情页完整内容：职场压力情绪管理技巧，科学调节情绪释放压力，保持积极好心态，生活更轻松",
                            label = listOf("压力", "情绪", "管理"),
                            imgUrl = "https://picsum.photos/600/300?random=95",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "96",
                            title = "简历制作优化技巧",
                            desc = "高分简历模板，面试通过率翻倍",
                            detailContent = "详情页完整内容：简历制作优化教程，专业模板+内容技巧，突出优势亮点，HR一眼看中，面试通过率暴涨",
                            label = listOf("简历", "面试", "求职"),
                            imgUrl = "https://picsum.photos/600/300?random=96",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "97",
                            title = "自制健康饮品教程",
                            desc = "无糖健康饮品，在家自制，好喝又养颜",
                            detailContent = "详情页完整内容：居家自制无糖健康饮品，水果茶养生饮，好喝不胖美容养颜，做法简单零失败",
                            label = listOf("饮品", "自制", "健康"),
                            imgUrl = "https://picsum.photos/600/300?random=97",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "98",
                            title = "阳台花园布置技巧",
                            desc = "小阳台变花园，花草种植，美观又治愈",
                            detailContent = "详情页完整内容：小阳台花园改造布置，花草搭配种植技巧，美观治愈，在家就能享受花园氛围",
                            label = listOf("阳台", "花园", "种植"),
                            imgUrl = "https://picsum.photos/600/300?random=98",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "99",
                            title = "动漫手办保养方法",
                            desc = "手办清洁保养技巧，长久保存不变形",
                            detailContent = "详情页完整内容：动漫手办保养清洁教程，防尘防掉色防变形，正确存放清洁，长久保存如新",
                            label = listOf("手办", "保养", "动漫"),
                            imgUrl = "https://picsum.photos/600/300?random=99",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "100",
                            title = "家庭酒水储存指南",
                            desc = "白酒红酒正确存放，保持口感不变质",
                            detailContent = "详情页完整内容：家庭白酒红酒储存方法，温湿度控制摆放方式，正确存放口感更佳，长久不变质",
                            label = listOf("酒水", "储存", "家庭"),
                            imgUrl = "https://picsum.photos/600/300?random=100",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "101",
                            title = "地方特色美食推荐",
                            desc = "各地正宗特产小吃，舌尖上的美味",
                            detailContent = "详情页完整内容：全国地方特色美食特产合集，正宗老字号口味，在家就能吃遍全国，舌尖美味超满足",
                            label = listOf("美食", "特产", "地方"),
                            imgUrl = "https://picsum.photos/600/300?random=101",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "102",
                            title = "古风舞蹈教学入门",
                            desc = "简单古风舞蹈，气质提升，零基础可学",
                            detailContent = "详情页完整内容：零基础古风舞蹈入门教程，动作简单优雅，提升气质，新手也能快速学会",
                            label = listOf("舞蹈", "古风", "入门"),
                            imgUrl = "https://picsum.photos/600/300?random=102",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "103",
                            title = "手工饰品制作教程",
                            desc = "自制精美饰品，独一无二，送礼超有面",
                            detailContent = "详情页完整内容：手工饰品制作教程，项链手链发饰，材料简单成品精美，独一无二送礼超有面子",
                            label = listOf("手工", "饰品", "制作"),
                            imgUrl = "https://picsum.photos/600/300?random=103",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "104",
                            title = "登山徒步装备推荐",
                            desc = "登山必备装备，安全舒适，户外爱好者必备",
                            detailContent = "详情页完整内容：登山徒步专业装备清单，鞋子背包护具，安全舒适轻量化，户外爱好者必备",
                            label = listOf("登山", "徒步", "装备"),
                            imgUrl = "https://picsum.photos/600/300?random=104",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "105",
                            title = "狗狗训练技巧教程",
                            desc = "听话狗狗训练法，简单有效，新手也会",
                            detailContent = "详情页完整内容：新手狗狗训练教程，定点排便坐下握手，简单指令一学就会，养出乖巧听话萌宠",
                            label = listOf("狗狗", "训练", "技巧"),
                            imgUrl = "https://picsum.photos/600/300?random=105",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "106",
                            title = "智能穿戴设备推荐",
                            desc = "手表手环测评，健康监测，运动必备",
                            detailContent = "详情页完整内容：高性价比智能手表手环测评，心率睡眠监测运动记录，健康管理小助手，日常必备",
                            label = listOf("智能", "穿戴", "健康"),
                            imgUrl = "https://picsum.photos/600/300?random=106",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "107",
                            title = "日常妆容快速打造",
                            desc = "5分钟快速出门妆，简约自然，新手易学",
                            detailContent = "详情页完整内容：5分钟快速日常妆容教程，步骤简单自然伪素颜，新手手残党也能轻松学会",
                            label = listOf("妆容", "快速", "日常"),
                            imgUrl = "https://picsum.photos/600/300?random=107",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "108",
                            title = "增肌健身餐食谱",
                            desc = "高蛋白健身餐，增肌不增脂，好吃管用",
                            detailContent = "详情页完整内容：健身增肌高蛋白食谱，荤素搭配好吃不胖，做法简单，增肌减脂效果拉满",
                            label = listOf("健身餐", "增肌", "高蛋白"),
                            imgUrl = "https://picsum.photos/600/300?random=108",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "109",
                            title = "职业资格考试攻略",
                            desc = "考证复习方法，高效备考，一次通关",
                            detailContent = "详情页完整内容：职业资格考试高效复习攻略，重点笔记+答题技巧，科学备考一次通关不二战",
                            label = listOf("考证", "考试", "职业"),
                            imgUrl = "https://picsum.photos/600/300?random=109",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "110",
                            title = "儿童益智玩具推荐",
                            desc = "开发智力玩具，亲子互动，宝宝超爱",
                            detailContent = "详情页完整内容：儿童益智玩具精选，开发大脑锻炼动手能力，亲子互动趣味十足，宝宝超喜欢",
                            label = listOf("儿童", "益智", "玩具"),
                            imgUrl = "https://picsum.photos/600/300?random=110",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "111",
                            title = "特色小吃制作教程",
                            desc = "街头小吃在家做，干净卫生，味道正宗",
                            detailContent = "详情页完整内容：网红街头小吃居家制作教程，食材简单做法方便，干净卫生无添加，味道超正宗",
                            label = listOf("小吃", "制作", "特色"),
                            imgUrl = "https://picsum.photos/600/300?random=111",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "112",
                            title = "高端腕表保养指南",
                            desc = "机械表保养方法，延长寿命，精准走时",
                            detailContent = "详情页完整内容：机械腕表专业保养指南，清洗调校防水维护，正确保养延长寿命，走时更精准",
                            label = listOf("腕表", "保养", "高端"),
                            imgUrl = "https://picsum.photos/600/300?random=112",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "113",
                            title = "办公效率神器推荐",
                            desc = "提升工作效率，办公必备，省时省力",
                            detailContent = "详情页完整内容：打工人办公效率神器合集，小工具大作用，提升工作效率，省时省力不加班",
                            label = listOf("办公", "效率", "神器"),
                            imgUrl = "https://picsum.photos/600/300?random=113",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "114",
                            title = "体态矫正训练课程",
                            desc = "改善驼背圆肩，提升气质，站姿更挺拔",
                            detailContent = "详情页完整内容：体态矫正专项训练，改善驼背圆肩脖子前伸，每天10分钟，提升气质身姿更挺拔",
                            label = listOf("体态", "矫正", "训练"),
                            imgUrl = "https://picsum.photos/600/300?random=114",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "115",
                            title = "新能源汽车测评",
                            desc = "电车选购攻略，续航充电，性价比分析",
                            detailContent = "详情页完整内容：2025新能源汽车全面测评，续航充电空间配置，性价比分析，新手买车不踩坑",
                            label = listOf("新能源", "汽车", "测评"),
                            imgUrl = "https://picsum.photos/600/300?random=115",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "116",
                            title = "装修避坑指南大全",
                            desc = "装修常见陷阱，省钱避坑，少走弯路",
                            detailContent = "详情页完整内容：装修全流程避坑指南，材料报价施工陷阱，省钱技巧，装修少走90%弯路",
                            label = listOf("装修", "避坑", "指南"),
                            imgUrl = "https://picsum.photos/600/300?random=116",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "117",
                            title = "手工编织教程分享",
                            desc = "毛线编织技巧，围巾包包，简单易学",
                            detailContent = "详情页完整内容：毛线手工编织教程，围巾包包杯套，新手零基础易学，成品温暖又好看",
                            label = listOf("编织", "手工", "毛线"),
                            imgUrl = "https://picsum.photos/600/300?random=117",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "118",
                            title = "电脑系统优化技巧",
                            desc = "电脑提速方法，告别卡顿，运行更流畅",
                            detailContent = "详情页完整内容：电脑系统优化提速教程，清理垃圾关闭启动项，老机重获新生，运行飞快不卡顿",
                            label = listOf("电脑", "优化", "提速"),
                            imgUrl = "https://picsum.photos/600/300?random=118",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "119",
                            title = "护发养发技巧分享",
                            desc = "改善脱发干枯，养出柔顺秀发",
                            detailContent = "详情页完整内容：科学护发养发技巧，改善脱发干枯毛躁，正确洗护方法，养出乌黑柔顺健康秀发",
                            label = listOf("护发", "养发", "美发"),
                            imgUrl = "https://picsum.photos/600/300?random=119",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "120",
                            title = "综艺搞笑名场面",
                            desc = "爆笑综艺片段，解压放松，欢乐不停",
                            detailContent = "详情页完整内容：全网综艺爆笑名场面合集，搞笑解压欢乐不断，休闲放松必看，笑到停不下来",
                            label = listOf("综艺", "搞笑", "爆笑"),
                            imgUrl = "https://picsum.photos/600/300?random=120",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "121",
                            title = "家庭清洁小妙招",
                            desc = "全屋清洁技巧，轻松去污，干净省力",
                            detailContent = "详情页完整内容：家庭全屋清洁妙招，油污灰尘水垢轻松去除，省时省力干净卫生，家务小白也能行",
                            label = listOf("清洁", "家庭", "妙招"),
                            imgUrl = "https://picsum.photos/600/300?random=121",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "122",
                            title = "定制纪念品推荐",
                            desc = "专属纪念礼品，刻字定制，意义非凡",
                            detailContent = "详情页完整内容：专属定制纪念品合集，照片刻字个性设计，纪念意义拉满，送礼自留都超有价值",
                            label = listOf("定制", "纪念", "礼品"),
                            imgUrl = "https://picsum.photos/600/300?random=122",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "123",
                            title = "轮滑滑板技巧教学",
                            desc = "新手入门技巧，炫酷好玩，运动健身",
                            detailContent = "详情页完整内容：轮滑滑板新手入门教程，基础滑行转弯刹车，炫酷好玩还能运动健身，老少皆宜",
                            label = listOf("轮滑", "滑板", "运动"),
                            imgUrl = "https://picsum.photos/600/300?random=123",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "124",
                            title = "养生汤品配方分享",
                            desc = "滋补养生汤，四季皆宜，全家都能喝",
                            detailContent = "详情页完整内容：家常滋补养生汤食谱，食材简单营养丰富，四季皆宜，养胃补气全家都能喝",
                            label = listOf("养生", "汤品", "滋补"),
                            imgUrl = "https://picsum.photos/600/300?random=124",
                            videoUrl = "",
                            type = 0,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "125",
                            title = "舒适睡衣推荐合集",
                            desc = "亲肤透气睡衣，居家舒适，颜值超高",
                            detailContent = "详情页完整内容：舒适亲肤睡衣合集，纯棉冰丝材质，透气柔软颜值高，居家睡觉超舒服",
                            label = listOf("睡衣", "舒适", "居家"),
                            imgUrl = "https://picsum.photos/600/300?random=125",
                            videoUrl = "",
                            type = 1,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "126",
                            title = "livehouse演出推荐",
                            desc = "小众现场演出，音乐氛围超棒，放松好去处",
                            detailContent = "详情页完整内容：高品质livehouse演出推荐，小众乐队现场，音乐氛围超棒，休闲放松打卡好去处",
                            label = listOf("演出", "音乐", "现场"),
                            imgUrl = "https://picsum.photos/600/300?random=126",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 1,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "127",
                            title = "平板数码配件推荐",
                            desc = "平板保护壳、笔、配件，实用又好看",
                            detailContent = "详情页完整内容：平板必备数码配件合集，保护壳手写笔钢化膜，实用美观性价比高，平板党必备",
                            label = listOf("平板", "配件", "数码"),
                            imgUrl = "https://picsum.photos/600/300?random=127",
                            videoUrl = "",
                            type = 0,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "128",
                            title = "游戏外设装备推荐",
                            desc = "机械键盘鼠标，电竞体验，手感超棒",
                            detailContent = "详情页完整内容：高性价比游戏外设装备，机械键盘鼠标耳机，电竞手感体验，打游戏更畅快",
                            label = listOf("外设", "电竞", "游戏"),
                            imgUrl = "https://picsum.photos/600/300?random=128",
                            videoUrl = "",
                            type = 1,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "129",
                            title = "儿童成长记录分享",
                            desc = "宝宝成长瞬间，温馨记录，美好回忆",
                            detailContent = "详情页完整内容：儿童成长珍贵瞬间记录，温馨治愈美好回忆，记录宝宝每一个可爱时刻",
                            label = listOf("儿童", "成长", "记录"),
                            imgUrl = "https://picsum.photos/600/300?random=129",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 2,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "130",
                            title = "线上副业赚钱项目",
                            desc = "靠谱副业推荐，空闲时间赚零花钱",
                            detailContent = "详情页完整内容：正规线上靠谱副业项目，空闲时间就能做，零门槛上手，轻松赚零花钱",
                            label = listOf("副业", "赚钱", "线上"),
                            imgUrl = "https://picsum.photos/600/300?random=130",
                            videoUrl = "",
                            type = 0,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "131",
                            title = "二手数码选购指南",
                            desc = "二手手机电脑选购，避坑技巧，性价比高",
                            detailContent = "详情页完整内容：二手数码产品选购避坑指南，验机技巧质量判断，花小钱买好货，性价比拉满",
                            label = listOf("二手", "数码", "选购"),
                            imgUrl = "https://picsum.photos/600/300?random=131",
                            videoUrl = "",
                            type = 1,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        ),
                        AdItem(
                            id = "132",
                            title = "厨房收纳清洁技巧",
                            desc = "厨房整洁收纳，油污清洁，干净清爽",
                            detailContent = "详情页完整内容：厨房收纳+油污清洁双攻略，空间整洁不杂乱，油污轻松去除，干净清爽超好用",
                            label = listOf("厨房", "收纳", "清洁"),
                            imgUrl = "https://picsum.photos/600/300?random=132",
                            videoUrl = "https://www.w3school.com.cn/example/html5/mov_bbb.mp4",
                            type = 2,
                            channelType = 0,
                            likeCount = 8932,
                            starCount = 678
                        )
                    )
                )


                    dao.insertAll(list)
                } else {
                    // 数据库已有数据，只重置点赞和收藏状态为 false（保留数量）
                    dao.resetAllLikeAndStar()
                }
            }
        }
    }
}